// <auto-generated />
using IdentityByCertificate.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdentityByCertificate.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230810130000_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.20");

            modelBuilder.Entity("IdentityByCertificate.Models.CertificateModel", b =>
                {
                    b.Property<string>("Thumbprint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Thumbprint");

                    b.ToTable("Certificates");
                });
#pragma warning restore 612, 618
        }
    }
}
